### ISSUE TITLE
research vue.js

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/ourhandsandfeet#363]

**Comment by freethlua** [comment]
To switch from Aurelia to VueJS? If you're exploring options have you considered React (I'm guessing you already have?), and [Preact], or [Hyperscript instead of JSX][1], and [Marko]? Just throwing some suggestions (that I've worked with and liked) in case you're still considering options.  I've no strong opinion on VueJS (heard good things about it). [In its comparison page][2] it mentions being the next step to React+[Mobx] which is actually what I've been using lately (Peact+MobX+Hyperscript) and would personally still prefer this combo over Vue or Marko, but would still love to work with either.

[preact]: https://github.com/developit/preact
[1]: https://medium.com/@jador/jsx-4b978fbeb290
[marko]: http://markojs.com/
[2]: https://vuejs.org/v2/guide/comparison.html#With-MobX
[Mobx]: https://mobx.js.org/

**Comment by JoshuaVSherman** [comment]
Thanks Freeth for the information. I'm sticking with Aurelia for now. Talk
to you later

**Comment by JoshuaVSherman** [comment]
Issue moved to [WebJamApps/combined-front #67](https://github.com/WebJamApps/combined-front/issues/67) via [**ZenHub**](https://www.zenhub.com/)
